Do while task support in builder
FRINXio/frinx-workflow-ui pull request #70
Opened 2020-10-15 09:55 UTC by marosmars

Do while task in conductor:
https://netflix.github.io/conductor/configuration/systask/#do-while-task

It is a simple while loop.
It cannot have nested loops or subworkflows in it.

Do while is not present in FM version of conductor and is disabled by
default.

Signed-off-by: Maros Marsalek <mmarsalek@frinx.io>

2020-10-15 09:59 UTC, marosmars commented
@ChmaraX I think I've modified all the places required for a new built-in task.
I also tested it manually with a bunch of workflows designed by hand.

but pls review if you can

2020-10-15 10:02 UTC, marosmars commented
Also, it wasn't easy adding support for a new built-in task ... I was thinking if we could do/think about refactoring the codebase to make it easier.

Currently the parsing (or model - model translation) is spread in too many places.
There are actually 3 different models for the workflow: UI model for react-diagrams, WFE model for workflow layout and the Conductor JSON model. But only one of them is formally defined (as classes and types) and that's the UI model for react-diagrams. Maybe we should do the same for the other models and then refactor the translations and put them under a single place (and use some patterns /if there are any/ for model2model translation).

and also add unit tests before doing anything, since without unit tests it is impossible to do big refactoring ...

what do you think ?

2020-10-15 10:41 UTC, ChmaraX commented
> what do you think ?

I agree and I'm well aware of what should be refactored (and its sadly not just this) but since this app was initially made in few weeks as a demo without prior specification (or any software dev method at all) and since then, only new features were added by multiple people (also without specification and testing), it now requires some design patterns and greater effort to improve code quality which im trying think of and slowly apply now on the go, since I was not familiar (and probably noone involved) with Javascript or React patterns and best practices at the time of writing this project and still I would be glad to receive feedback/suggestions from more senior members on actual code implementation rather than on just visual side :)

TL'DR: it's a good idea, it should be discussed and prioritized, but it should come as a specific task, it doesn't matter what I think since its not my personal project

2020-10-16 07:11 UTC, marosmars commented
I created an issue for refactoring
https://github.com/FRINXio/frinx-workflow-ui/issues/71

We should list specific things that need to be refactored/fixed ... then we can decide what to do with it 
So if you have anything specific, please list it there

2020-10-16 12:47 UTC, ChmaraX requested changes
I think it would be maybe better to have loop condition in "Input Parameters" tab or outside "Advanced parameters" similiar to other system tasks.

2020-10-16 12:47 UTC, ChmaraX commented on src/pages/diagramBuilder/WorkflowDiagram.js
> +            parentNode = this.parseTaskToJSON(link, parentNode, loopTasks);
`link` is `null` in probably last iteration, therefore it cant finish traversing through nodes and finish mapping of nodes into JSON

`Error: Cannot read property 'sourcePort' of null`

2020-10-22 14:02 UTC, marosmars commented on src/pages/diagramBuilder/WorkflowDiagram.js
> +            parentNode = this.parseTaskToJSON(link, parentNode, loopTasks);
Fixed finally, isWhileEnd was checking wrong task type ... do_while_end instead of while_end

2020-10-22 14:15 UTC, marosmars commented
> I think it would be maybe better to have loop condition in "Input Parameters" tab or outside "Advanced parameters" similiar to other system tasks.

I guess ... but it is not an inputParameter, the task definition requires that outside of inputParams. So the fact that it ends up in advanced parameters is because it is not in inputParameters as defined in Sidebar.js

Would that still be possible ?

2020-10-23 12:12 UTC, ChmaraX approved these changes

2020-10-23 12:25 UTC, merged